---
# Services to enable
_kvm_services_enable:
  all: []
  CentOS_7:
    - libvirtd
  RedHat_7:
    - libvirtd
  CentOS_8:
    - libvirtd
  RedHat_8:
    - libvirtd
  Fedora_31:
    - libvirtd
  Debian_10:
    - libvirtd
  Ubuntu_18:
    - libvirtd
