---
# Template configuration files for kvm

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  with_items: "{{ kvm_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - kvm_enable_selinux
  become: true
